platform :ios, '14.1'

use_modular_headers!
inhibit_all_warnings!

target 'Volrota' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  #Routing 
  pod 'XCoordinator', '~> 2.0'

  #Other
  pod 'SnapKit'
  pod 'SwiftGen'

end
