platform :ios, '14.1'

use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'Volrota' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  #Routing 
  pod 'XCoordinator', '~> 2.0'

  #Other
  pod 'SnapKit'
  pod 'SwiftGen'
  pod 'lottie-ios'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'

  #Firebase
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage' 
  pod 'FirebaseFirestoreSwift'

  #Keychain
  pod 'KeychainAccess'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
