platform :ios, '14.1'

use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'Volrota' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  #Routing 
  pod 'XCoordinator', '~> 2.0'

  #Other
  pod 'SnapKit'
  pod 'SwiftGen'
  pod 'lottie-ios'
  pod 'Kingfisher'

  #Firebase
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

end
